version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    command:
      --server-id=1
      --binlog-format=ROW
      --binlog-row-image=full
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: bw
      MYSQL_PASSWORD: bw
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - /mysql:/var/lib/mysql
 
  mysql-sink:
    container_name: mysql-sink
    image: mysql:8.0
    ports:
      - "3307:3306"
    command:
      --server-id=2
      --binlog-format=ROW
      --binlog-row-image=full
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: bw
      MYSQL_PASSWORD: bw
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - /mysql-sink:/var/lib/mysql    
     
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
