services:
    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - 3306:3306
        command:
            --server-id=1
            --binlog-format=ROW
            --binlog-row-image=full
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_USER: bw
            MYSQL_PASSWORD: bw
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
