services:
  zookeeper:
    container-name: zookeeper
    image: confluent/zookeeper
    ports:
      - "2181:2181"
      
  kafka:
    comtainer-name: kafka
    image: confluent/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
